### PR TITLE
Improve UI.

### LINKED ISSUE #2: Better UI
Currently, there's way too much boilerplate in the Podfile, it should just be

```ruby
pod 'Alamofire'
```

also the command is kinda longish. So ideally, one would do something like:

```bash
$ pod bootstrap
```

and that would amend the Podfile for consumption by the actual `pod install` and also pass the extra arguments to it.

### PR DESCRIPTION
**Pull request by neonichu**
Fixes #2 

@segiddins Can you take a look? Is there a better way to check if the plugin has been activated?

### CODE REVIEW

**Comment by segiddins** [comment]
I really really dislike all this monkey patching

**Comment by neonichu** [comment]
Me, too - other ideas? It could be a dedicated command, but there'd still be the `use_frameworks!` thing. Maybe even use a different file, `Romefile` that would assume frameworks?

**Comment by segiddins** [comment]
Just print out an error if the user didn't use frameworks?

-Samuel E. Giddins

On Apr 2, 2015, at 8:41 AM, Boris Bügling <notifications@github.com> wrote:

Me, too - other ideas? It could be a dedicated command, but there'd still be the use_frameworks! thing. Maybe even use a different file, Romefile that would assume frameworks?

**Comment by neonichu** [comment]
Well, the goal is to be able to omit `use_frameworks!`, because it doesn't make sense to use Rome without.

**Comment by segiddins** [comment]
Rome should be subservient to the Podfile, not the other way around. 

-Samuel E. Giddins

On Apr 2, 2015, at 8:49 AM, Boris Bügling <notifications@github.com> wrote:

Well, the goal is to be able to omit use_frameworks!, because it doesn't make sense to use Rome without.

**Comment by neonichu** [comment]
Yes and no, it makes no sense to me to require the user to add superfluous things to the Podfile.

Since specifying the Rome plugin already makes the Podfile unusable for a regular `pod install`, I kinda like the idea of a `Romefile` which would simply imply `use_frameworks!` and usage of the Rome plugin. A separate command (e.g. `pod rome install`) could impose the default configuration, transform the file to a Podfile and then call the regular installer. It would also clearly separate this action from a regular installation.

**Comment by segiddins** [comment]
I also really dislike adding a new file. What's wrong with just specifying the use_frameworks flag?

-Samuel E. Giddins

On Apr 2, 2015, at 9:09 AM, Boris Bügling <notifications@github.com> wrote:

Yes and no, it makes no sense to me to require the user to add superfluous things to the Podfile.

Since specifying the Rome plugin already makes the Podfile unusable for a regular pod install, I kinda like the idea of a Romefile which would simply imply use_frameworks! and usage of the Rome plugin. A separate command (e.g. pod rome install) could impose the default configuration, transform the file to a Podfile and then call the regular installer. It would also clearly separate this action from a regular installation.

**Comment by neonichu** [comment]
Nothing really, except my stubbornness to not want to specify it 😛

**Comment by orta** [comment]
if it was me, I would do this

**Comment by orta** [comment]
You may be able to use the pre-installer hooks in 0.38 BTW

**Comment by segiddins** [comment]
This is no longer necessary?

**Comment by neonichu** [comment]
Yah, it's not.

**Pull request closed without merging**
