### PR TITLE
Add a pre-install hook to force frameworks and --no-integrate

### LINKED ISSUE #2: Better UI
Currently, there's way too much boilerplate in the Podfile, it should just be

```ruby
pod 'Alamofire'
```

also the command is kinda longish. So ideally, one would do something like:

```bash
$ pod bootstrap
```

and that would amend the Podfile for consumption by the actual `pod install` and also pass the extra arguments to it.

### LINKED ISSUE #14: Enforce use of `use_frameworks!`
Either complain when it isn't there or do #2

Currently, the `mv` will just fail.

### PR DESCRIPTION
**Pull request by segiddins**
Closes #2.
Closes #14.

### CODE REVIEW

**Comment by keith** [comment]
:+1:

**Comment by segiddins** [comment]
\c @neonichu

**Comment by neonichu** [comment]
:+1:

I'm thinking we should also remove the `--no-integrate` from the README.

**Comment by segiddins** [comment]
Done

**Pull request merged**
